server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost/cashier?useSSL=false
    username: dbuser
    password: nacs
  jpa:
    hibernate:
      ddl-auto: update

info:
  priceList:
    capuccino: 1.5
    espresso: 1.00