game:
  moves:
    - name: rock
      defeats: scissors lizard
    - name: lizard
      defeats: spock paper
    - name: scissors
      defeats: paper lizard
    - name: paper
      defeats: rock spock
    - name: spock
      defeats: scissors rock
