server:
  port: 9003

addmimssion:
    server:
      url: http://localhost:9002/patients
info:
  treatments:
    Migraine: BloodtestsComputerizedTomographyScan
    Migraine1: 1BloodtestsComputerizedTomographyScan1
    Migraine2: 2BloodtestsComputerizedTomographyScan2