server:
  port: 9003

accountancy:
    server:
      url: http://localhost:9005/patients
info:
  treatments:
    getrest: 3daysREst
    heartattack: operation

spring:
  data:
    mongodb:
      uri: mongodb://localhost/drhouse-beds
