server:
  port: 9003

accountancy:
    server:
      url: http://localhost:9005/patients
info:
  treatments:
    Migraine: BloodtestsComputerizedTomographyScan
    Migraine2: 1BloodtestsComputerizedTomographyScan2
