server:
  port: 9005

spring:
  datasource:
    url: jdbc:mysql://localhost/drhouse-accountancy?useSSL=false
    username: nacsuser
    password: nacs
  jpa:
    hibernate:
      ddl-auto: update
accountancy:
  prices:
    - provided: Migrainemedicament
      price: 120
    - provided: coldmedicament
      price: 40
    - provided: 3 days Rest
      price: 120
    - provided: 3 days in bed
      price: 20
    - provided: operation
      price: 440

