server:
  port: 9005

spring:
  datasource:
    url: jdbc:mysql://localhost/drhouse-accountancy?useSSL=false
    username: nacsuser
    password: nacs
  jpa:
    hibernate:
      ddl-auto: update

info:
  prices:
    1BloodtestsComputerizedTomographyScan2: 120
    Migraine1Tablet1: 40
    BloodtestsComputerizedTomographyScan: 1220
    Migraine3Tablet3: 440
