server:
  port: 9002

bed:
  server:
    url: http://localhost:9003/patients

pharmacy:
  server:
    url: http://localhost:9004/patients

dataset:
  diagnosis:
    headache: Migraine
    headache1: Migraine1
    headache2: Migraine2
    headache3: Migraine3

direction:
  directions:
      Migraine: bed
      Migraine1: pharmacy
      Migraine2: bed
      Migraine3: pharmacy